### ISSUE TITLE
Todo March: PoC for validation

### ISSUE THREAD

**Issue by EAT-CODE-KITE-REPEAT** [EAT-CODE-KITE-REPEAT/Dunbar#1]
I got this Aha-eureka moment when I started thinking about this, at about 22:30 on a lonely friday night. How do I maintain my relationships? Well, it's hard. All current platforms don't really help you with it. If they do anything, they make it harder. I really think there should exist a tool to easily see and maintain the relationships that you care about. To create a PoC I just need a very simple offline app that can get some contacts from my contact list, put them on a screen, and have a cool UI that has leads to real human interaction. 

Publish (3h)
- [x] Publish
- [x] Create icon and splash screen
- [x] Make sure reason for permission is given
- [x] Build Android and iOS
- [x] Go through review process
- [x] Add picture for everyone
- [x] Create screenshots of first 2 tabs (and with action sheet open)
- [x] Create description

Add/Edit screen (2h)
- [x] Install react-native-data-forms
- [x] Make it work with newest expo
- [x] Setup firebase image upload for this project
- [x] Add user screen to add/edit a contact (use leckr-inputs + data-forms)
- [x] pass user to userscreen
- [x] create form with important contactfields, including name, number, email, image and notes
- [x] create reducer UPSERT_USER
- [x] submitting will map data right, UPSERT to reduxstore, 
- [x] make a promise of dispatcher function
- [x] Test if it works
- [x] Fix bug that new contacts don't receive all data (add saveAll prop)
- [x] Maybe save a smaller version of the image

leckr-inputs (Don't count time):
- [x] Fix TextArea crash RN.58

Keypad Screen (1h)
- [x] create keypad screen to type in new number and call or add
- [x] make call always work
- [x] link to add contact based on number when typing in new number
- [x] test on multiple screensizes, fix wrapping max 3 keys and alter padsize based on height too

Contact Screen (3h)
- [x] add search bar which filters contacts, same view (don’t change selection state)
- [x] add selection onPress (add to selection state)
- [x] add edit button which hides or shows selecting
- [x] add link to user screen onclick when not editing
- [x] Create save actions as FAB's: Favorite, Unfavorite or Delete (based on selection)
- [x] Fav FAB -> redux add reducer
- [x] Unfav FAB -> redux remove reducer
- [x] Delete FAB -> ContactsApi.removecontact
- [x] Make difference between intro contactsscreen and normal contactsscreen
- [x] Put a yellow star next to your selected people
- [x] Show actions after at least 1 is selected
- [x] Add kav
- [x] Add bottom padding to prevent overlapping last contacts with FAB's
- [x] add pull to refresh which syncs contacts

Home Screen (2h)
- [x] create user card UI
- [x] Add superactionsheet for all actions, open on click
- [x] Longpress to prefered option (whatsapp, phone, or profile)
- [x] wrap long names

Workflow (0h)
- [X] Make github repo
- [x] Setup [ESLint](https://github.com/airbnb/javascript/issues/1589)

Navigation (1h)
- [x] Add navigation icons
- [x] Fix weird RN tabs-required problem [use this guide, add switch nav](https://reactnavigation.org/docs/en/auth-flow.html)
- [x] Remove tab-text
- [x] add title on every tab or navigated screen
- [x] style button right for android (everywhere)

Redux Data Store (1h)
- [x] in index, make sure store is given to screenProps or wrapped around every screen
- [X] Create redux store and reducer. 
- [X] We keep all data too (instead of just ID) because we want it on backend too, in the long-term. Don't do this yet, though for the MVP
- [x] Add field for introSeen and use it

Intro screen (1h)
- [x] Add some images to support texts

More Tab (1h)
- [x] Create more-tab with about, settings, team

About the creator (0h)
- [x] Add screen about the author (me) and a way to contact me

I really think this is a breakthrough idea. 
But I need to validate more first. 

Hours spent:
- [x] week 10: 8
- [x] week 11, monday: 4, tuesday: 4, wednesday: 6, saturday: 2
- [x] hours left: 1
